CREATE TABLE IF NOT EXISTS eval_task (
  task_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_name VARCHAR(120) NOT NULL,
  agent_version VARCHAR(32) NOT NULL,
  dataset_id VARCHAR(120) NOT NULL,
  metric_set CLOB,
  status VARCHAR(24) NOT NULL,
  created_at TIMESTAMP NOT NULL,
  evaluation_mode VARCHAR(24) NOT NULL,
  evaluation_method VARCHAR(24) NOT NULL,
  evaluation_dimensions VARCHAR(128) NOT NULL,
  strategy_config CLOB,
  strategy_version BIGINT
);

CREATE TABLE IF NOT EXISTS eval_run (
  run_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id BIGINT NOT NULL,
  status VARCHAR(24) NOT NULL,
  start_time TIMESTAMP,
  end_time TIMESTAMP,
  total_count INT,
  success_count INT,
  fail_count INT,
  CONSTRAINT fk_eval_run_task FOREIGN KEY (task_id) REFERENCES eval_task(task_id)
);

CREATE TABLE IF NOT EXISTS qa_record (
  qa_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id BIGINT NOT NULL,
  input CLOB NOT NULL,
  expected_output CLOB,
  actual_output CLOB,
  tool_trace CLOB,
  first_token_latency_ms BIGINT,
  end_to_end_latency_ms BIGINT,
  token_usage CLOB,
  error_code VARCHAR(64),
  error_message CLOB,
  CONSTRAINT fk_qa_record_run FOREIGN KEY (run_id) REFERENCES eval_run(run_id)
);

CREATE TABLE IF NOT EXISTS metric_snapshot (
  snapshot_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id BIGINT NOT NULL UNIQUE,
  task_completion_rate DOUBLE,
  tool_correctness_score DOUBLE,
  tool_efficiency_score DOUBLE,
  first_token_p95 BIGINT,
  end_to_end_p95 BIGINT,
  total_tokens BIGINT,
  effectiveness_score DOUBLE,
  safety_score DOUBLE,
  performance_score DOUBLE,
  judge_reason CLOB,
  CONSTRAINT fk_metric_snapshot_run FOREIGN KEY (run_id) REFERENCES eval_run(run_id)
);

CREATE TABLE IF NOT EXISTS eval_strategy (
  strategy_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  strategy_name VARCHAR(120) NOT NULL,
  metric_definitions CLOB,
  weight_config CLOB,
  threshold_config CLOB,
  created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS eval_strategy_version (
  strategy_version_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  strategy_id BIGINT NOT NULL,
  version INT NOT NULL,
  metric_definitions CLOB,
  weight_config CLOB,
  threshold_config CLOB,
  created_at TIMESTAMP NOT NULL,
  CONSTRAINT uq_strategy_version UNIQUE (strategy_id, version),
  CONSTRAINT fk_strategy_version_strategy FOREIGN KEY (strategy_id) REFERENCES eval_strategy(strategy_id)
);

CREATE TABLE IF NOT EXISTS custom_metric (
  custom_metric_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  metric_name VARCHAR(120) NOT NULL,
  metric_type VARCHAR(24) NOT NULL,
  input_fields CLOB,
  scoring_logic CLOB,
  threshold_value DOUBLE,
  enabled BOOLEAN NOT NULL,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS eval_export_task (
  export_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id BIGINT NOT NULL,
  baseline_run_id BIGINT NOT NULL,
  target_run_id BIGINT NOT NULL,
  changed_only BOOLEAN NOT NULL,
  format VARCHAR(16) NOT NULL,
  status VARCHAR(24) NOT NULL,
  file_name VARCHAR(256),
  file_path VARCHAR(1024),
  message VARCHAR(1024),
  created_by VARCHAR(128),
  source VARCHAR(64),
  source_ip VARCHAR(128),
  last_operator VARCHAR(128),
  last_operation_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL,
  completed_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS eval_export_audit (
  audit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  export_id BIGINT NOT NULL,
  action VARCHAR(64) NOT NULL,
  operator VARCHAR(128),
  source_ip VARCHAR(128),
  detail VARCHAR(1024),
  created_at TIMESTAMP NOT NULL
);

-- ===== BT 多模型评测扩展（Step 1） =====

CREATE TABLE IF NOT EXISTS model_profile (
  model_profile_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  model_id VARCHAR(120) NOT NULL UNIQUE,
  display_name VARCHAR(120) NOT NULL,
  provider VARCHAR(64) NOT NULL,
  api_base_url VARCHAR(256),
  api_key_ref VARCHAR(64),
  role VARCHAR(24) NOT NULL,
  default_params CLOB,
  enabled BOOLEAN NOT NULL,
  created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS eval_comparison (
  comparison_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id BIGINT NOT NULL,
  sample_index INT NOT NULL,
  dimension VARCHAR(32) NOT NULL,
  model_a_id BIGINT NOT NULL,
  model_b_id BIGINT NOT NULL,
  qa_record_a_id BIGINT,
  qa_record_b_id BIGINT,
  position_swap BOOLEAN NOT NULL,
  result VARCHAR(16) NOT NULL,
  judge_model_id BIGINT,
  judge_reason VARCHAR(512),
  judge_latency_ms BIGINT,
  judge_prompt_tokens BIGINT,
  judge_completion_tokens BIGINT,
  created_at TIMESTAMP NOT NULL,
  CONSTRAINT fk_eval_comparison_run FOREIGN KEY (run_id) REFERENCES eval_run(run_id)
);

CREATE TABLE IF NOT EXISTS model_rating (
  rating_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id BIGINT NOT NULL,
  model_profile_id BIGINT NOT NULL,
  dimension VARCHAR(32) NOT NULL,
  theta DOUBLE,
  elo DOUBLE,
  lower_ci_95 DOUBLE,
  upper_ci_95 DOUBLE,
  n_comparisons INT,
  n_wins DOUBLE,
  win_rate DOUBLE,
  avg_latency_ms BIGINT,
  avg_tokens BIGINT,
  completion_rate DOUBLE,
  created_at TIMESTAMP NOT NULL,
  CONSTRAINT fk_model_rating_run FOREIGN KEY (run_id) REFERENCES eval_run(run_id)
);

-- 已有表加列（H2 支持 ALTER ... IF NOT EXISTS）
ALTER TABLE eval_task ADD COLUMN IF NOT EXISTS selected_model_ids CLOB;
ALTER TABLE eval_task ADD COLUMN IF NOT EXISTS judge_model_id BIGINT;
ALTER TABLE eval_task ADD COLUMN IF NOT EXISTS comparison_sampling_strategy VARCHAR(24);
ALTER TABLE eval_task ADD COLUMN IF NOT EXISTS position_swap_enabled BOOLEAN;

ALTER TABLE qa_record ADD COLUMN IF NOT EXISTS model_profile_id BIGINT;

-- ===== Dataset 数据集（Step 9 新增） =====

CREATE TABLE IF NOT EXISTS dataset (
  dataset_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(120) NOT NULL UNIQUE,
  display_name VARCHAR(120),
  source VARCHAR(24) NOT NULL,
  owner VARCHAR(120),
  sample_count INT,
  schema_hash VARCHAR(64),
  description VARCHAR(512),
  enabled BOOLEAN NOT NULL,
  created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS dataset_sample (
  sample_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dataset_id BIGINT NOT NULL,
  sample_key VARCHAR(64),
  input CLOB NOT NULL,
  expected_output CLOB,
  meta CLOB,
  sort_order INT,
  CONSTRAINT fk_dataset_sample_dataset FOREIGN KEY (dataset_id) REFERENCES dataset(dataset_id)
);
