CREATE TABLE IF NOT EXISTS eval_task (
  task_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_name VARCHAR(120) NOT NULL,
  agent_version VARCHAR(32) NOT NULL,
  dataset_id VARCHAR(120) NOT NULL,
  metric_set CLOB,
  status VARCHAR(24) NOT NULL,
  created_at TIMESTAMP NOT NULL,
  evaluation_mode VARCHAR(24) NOT NULL,
  evaluation_method VARCHAR(24) NOT NULL,
  evaluation_dimensions VARCHAR(128) NOT NULL,
  strategy_config CLOB,
  strategy_version BIGINT
);

CREATE TABLE IF NOT EXISTS eval_run (
  run_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id BIGINT NOT NULL,
  status VARCHAR(24) NOT NULL,
  start_time TIMESTAMP,
  end_time TIMESTAMP,
  total_count INT,
  success_count INT,
  fail_count INT,
  CONSTRAINT fk_eval_run_task FOREIGN KEY (task_id) REFERENCES eval_task(task_id)
);

CREATE TABLE IF NOT EXISTS qa_record (
  qa_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id BIGINT NOT NULL,
  input CLOB NOT NULL,
  expected_output CLOB,
  actual_output CLOB,
  tool_trace CLOB,
  first_token_latency_ms BIGINT,
  end_to_end_latency_ms BIGINT,
  token_usage CLOB,
  error_code VARCHAR(64),
  error_message CLOB,
  CONSTRAINT fk_qa_record_run FOREIGN KEY (run_id) REFERENCES eval_run(run_id)
);

CREATE TABLE IF NOT EXISTS metric_snapshot (
  snapshot_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id BIGINT NOT NULL UNIQUE,
  task_completion_rate DOUBLE,
  tool_correctness_score DOUBLE,
  tool_efficiency_score DOUBLE,
  first_token_p95 BIGINT,
  end_to_end_p95 BIGINT,
  total_tokens BIGINT,
  effectiveness_score DOUBLE,
  safety_score DOUBLE,
  performance_score DOUBLE,
  judge_reason CLOB,
  CONSTRAINT fk_metric_snapshot_run FOREIGN KEY (run_id) REFERENCES eval_run(run_id)
);

CREATE TABLE IF NOT EXISTS eval_strategy (
  strategy_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  strategy_name VARCHAR(120) NOT NULL,
  metric_definitions CLOB,
  weight_config CLOB,
  threshold_config CLOB,
  created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS eval_strategy_version (
  strategy_version_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  strategy_id BIGINT NOT NULL,
  version INT NOT NULL,
  metric_definitions CLOB,
  weight_config CLOB,
  threshold_config CLOB,
  created_at TIMESTAMP NOT NULL,
  CONSTRAINT uq_strategy_version UNIQUE (strategy_id, version),
  CONSTRAINT fk_strategy_version_strategy FOREIGN KEY (strategy_id) REFERENCES eval_strategy(strategy_id)
);

CREATE TABLE IF NOT EXISTS custom_metric (
  custom_metric_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  metric_name VARCHAR(120) NOT NULL,
  metric_type VARCHAR(24) NOT NULL,
  input_fields CLOB,
  scoring_logic CLOB,
  threshold_value DOUBLE,
  enabled BOOLEAN NOT NULL,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS eval_export_task (
  export_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id BIGINT NOT NULL,
  baseline_run_id BIGINT NOT NULL,
  target_run_id BIGINT NOT NULL,
  changed_only BOOLEAN NOT NULL,
  format VARCHAR(16) NOT NULL,
  status VARCHAR(24) NOT NULL,
  file_name VARCHAR(256),
  file_path VARCHAR(1024),
  message VARCHAR(1024),
  created_by VARCHAR(128),
  source VARCHAR(64),
  source_ip VARCHAR(128),
  last_operator VARCHAR(128),
  last_operation_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL,
  completed_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS eval_export_audit (
  audit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  export_id BIGINT NOT NULL,
  action VARCHAR(64) NOT NULL,
  operator VARCHAR(128),
  source_ip VARCHAR(128),
  detail VARCHAR(1024),
  created_at TIMESTAMP NOT NULL
);
